# Generated by Django 5.1.15 on 2026-06-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_headline', models.CharField(default="Dasturlashni o'rgan. Yerda, haqiqatda.", max_length=200)),
                ('hero_sub', models.CharField(default="IT Park tarmog'ining Yaypandagi markazi. Kichik guruhlar. Amaliy ta'lim.", max_length=300)),
                ('about_text', models.TextField(default="IT Center Yaypan — Farg'ona viloyatining Yaypan tumanida joylashgan texnologiya ta'lim markazi. IT Park tarmog'ining bir qismi sifatida faoliyat yuritamiz. Maqsadimiz — dasturlash va raqamli ko'nikmalarni hududdagi yoshlarga yetkazish.")),
                ('address', models.CharField(default="Yaypan tumani, Farg'ona viloyati", max_length=300)),
                ('phone', models.CharField(default='+998 XX XXX XX XX', max_length=50)),
                ('telegram_url', models.URLField(blank=True, default='https://t.me/itcenteryaypan')),
                ('instagram_url', models.URLField(blank=True)),
                ('working_hours', models.CharField(default='Du-Ju: 09:00-18:00, Sha: 10:00-15:00', max_length=100)),
                ('google_maps_embed_url', models.URLField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
