# Generated by Django 6.0.6 on 2026-06-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_headline',
            field=models.CharField(default='AyTi olamiga birinchi qadam.', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(default='+998 90 058 68 55', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='working_hours',
            field=models.CharField(default='Dushanba-Shanba: 08:00-18:00', max_length=100),
        ),
    ]
