# Generated by Django 6.0.6 on 2026-06-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitesettings_hero_headline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_typed_words',
            field=models.CharField(default="Dasturlash, Backend, Grafik dizayn, Python, Sun'iy intellekt", help_text="Bosh sahifadagi yozilib-o'chiriladigan so'zlar, vergul bilan ajrating", max_length=300),
        ),
    ]
