# Generated by Django 5.1.15 on 2026-06-08 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ism")),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon raqam')),
                ('message', models.TextField(blank=True, verbose_name='Xabar (ixtiyoriy)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('yangi', 'Yangi'), ('korib_chiqilmoqda', "Ko'rib chiqilmoqda"), ('qabul_qilindi', 'Qabul qilindi'), ('rad_etildi', 'Rad etildi')], default='yangi', max_length=30)),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin izohi (ichki)')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='courses.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
