# Generated by Django 5.1.15 on 2026-06-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('role', models.CharField(help_text="Masalan: Python Backend o'qituvchisi", max_length=200)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/')),
                ('telegram', models.CharField(blank=True, help_text='Masalan: @username', max_length=100)),
                ('linkedin', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('courses', models.ManyToManyField(blank=True, related_name='teachers', to='courses.course')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['order', 'full_name'],
            },
        ),
    ]
