# Generated by Django 5.1.15 on 2026-06-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tagline', models.CharField(help_text="Qisqa, ta'sirchan bir qator", max_length=150)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('icon_emoji', models.CharField(default='💻', help_text='Emoji icon, masalan: 🎨', max_length=10)),
                ('duration', models.CharField(help_text='Masalan: 3 oy', max_length=50)),
                ('schedule', models.CharField(help_text='Masalan: Du-Cho-Ju 15:00-17:00', max_length=100)),
                ('price', models.CharField(help_text="Masalan: Bepul yoki 450 000 so'm/oy", max_length=100)),
                ('level', models.CharField(choices=[('boshlangich', "Boshlang'ich"), ('orta', "O'rta"), ('ilgor', "Ilg'or")], default='boshlangich', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['order', 'name'],
            },
        ),
    ]
