# Generated by Django 6.0.6 on 2026-06-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='badge_text',
            field=models.CharField(blank=True, default='', help_text="Qizil shoshilinch belgi, masalan: 3 ta joy qoldi (bo'sh = ko'rsatilmaydi)", max_length=50),
        ),
    ]
