# Generated by Django 5.1.15 on 2026-06-08 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='Masalan: Python dasturchisi', max_length=200)),
                ('description', models.TextField()),
                ('avg_salary_range', models.CharField(help_text='Masalan: $400-800/oy', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_paths', to='courses.course')),
            ],
            options={
                'verbose_name': 'Career Path',
                'verbose_name_plural': 'Career Paths',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CareerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='career/companies/')),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='career.careerpath')),
            ],
            options={
                'verbose_name': 'Career Company',
                'verbose_name_plural': 'Career Companies',
            },
        ),
    ]
